#!/bin/bash

mkdir ~/.pipedroid 2> /dev/null
CFG=~/.pipedroid
mv ${CFG}/pipedroid.log ${CFG}/pipedroid.log.1 2> /dev/null
touch ${CFG}/pipedroid.log

function debug {
    echo "$1" | while read line;
        do 
        echo "$(date +%T) pipedroid: $line" >> ${CFG}/pipedroid.log
    done
    if [ -e "${CFG}/debug" ];
        then
        echo "$1" 1>&2
    fi
}

date >> ${CFG}/pipedroid.log
echo "Using $CFG as config directory."

debug "Looking for EasyBashGUI..."
source easybashgui || (echo "EBG not found. Get it from here: https://github.com/BashGui/easybashgui"; exit 1)

wait_for "Restarting ADB..."
adb kill-server
adb start-server
terminate_wait_for

message "Please disconnect ALL Android devices EXCEPT the one you want to back up.\nPlease also make sure all network-ADB devices are disconnected.\nIf you need to connect one, do it NOW and disconnect all USB devices.\nAlso, if you're not running CyanogenMod, make sure the device is rooted, BusyBox is installed and ADB is enabled.\nIf you're in recovery, either make sure the partition you want to backup is mounted or you know it's device path.\n\n$(adb devices)\n\n(if this window is too long, use Alt+Drag to move it and reach the Ok button on the bottom."

wait_for "Checking root..."
case "$(adb shell su -c "id -u")" in
    *"not found"*)
        su="sh"
        if [ "$(adb shell id -u | sed 's/[^0-9]//g')" == "0" ]
            then
            exco=0
        else
            exco=1
        fi
    ;;
    *0*)
        su="su"
        if [ "$(adb shell su -c "id -u" | sed 's/[^0-9]//g')" == "0" ]
            then
            exco=0
        elif grep -q "uid=0" <<< "$(adb shell su -c "id -u")";
            then
            exco=0
        else
            exco=1
        fi
    ;;
    *)
        su="su"
        exco=1
    ;;
esac
terminate_wait_for

if [ "$exco" != "0" ];
    then
    question "You're device seems not rooted.\n\nIs that a mistake? If you think it's a mistake, click Yes/Ok to go on anyway at your own risk."
    answer="${?}"
    if [ ${answer} -eq 0 ]
        then
        debug "User says the device is rooted."
    else
        debug "Device was not rooted."
        exit 1
    fi
else
    debug "The device is rooted."
fi

ok_message "In the next dialog, please select the backup format (more options will be added at some point).\n\nDO NOT DOUBLE CLICK: select the menu item then press Ok (it's a bug)"

tagged_menu  "raw" "Raw filesystem image" #"tar" "Tarball"
format="$(0< "${dir_tmp}/${file_tmp}" )"

if [ ${format} -eq "" ]
    then
    exit 2
fi

debug "Backup format choosen: ${format}"

ok_message "In the next dialog you'll be given the list of mountpoints in your device. Select the partition you want to backup.\n\nPlease note that in newer Android devices the internal storage is located inside of the userdata partition, in the following path: /data/media/0"

partlist="$(adb shell cat /proc/mounts | awk '{print $1,$2;}' | grep -e  ^/dev | grep -v fuse)
Custom"

OLDIFS="$IFS"
IFS="$(echo -e "\n")"
menu $partlist
IFS="$OLDIFS"
part="$(awk '{print $1;}' < "${dir_tmp}/${file_tmp}")"

if [ "${part}" == "" ]
    then
    exit 2
elif [ "$part" == "Custom" ]
    then
    input 1 "Enter here the partition's block device"
    part="$(0< "${dir_tmp}/${file_tmp}" )"
fi

debug "Partition choosen: ${part}"

ok_message "In the next dialog, please choose the compression method you prefer.\n\nIf you don't know what to pick, here there's a detailed explanation of what they do:\n\nhttps://github.com/Davideddu/pipedroid#compression-methods\n\nDO NOT DOUBLE CLICK: select the menu item then press Ok (it's a bug)"

tagged_menu "recompress" "Compress remotely, decompress and recompress locally (recommended)" "decompress" "Compress remotely, decompress locally" "keep_compressed" "Compress remotely, keep compressed (can't monitor progress)" "no_compression" "No compression at all (slow)"
compression="$(0< "${dir_tmp}/${file_tmp}" )"

debug "Compression method: ${compression}"

ok_message "In the next dialog select the destination file."

fselect
dest="$(0< "${dir_tmp}/${file_tmp}" )"

if [ ${dest} -eq "" ]
    then
    exit 2
fi

debug "Output file: ${dest}"

question "This is the last confirmation before actually starting the backup. Here's the information collected:\n\nPartition: ${part}\nFormat: ${format}\nCompression method: ${compression}\nOutput: ${dest}\n\nIs the information correct?\nClick Ok/Yes to start the backup."
answer="${?}"
if [ ! ${answer} -eq 0 ]
    then
    message "Please run the program again if the info was not correct."
    debug "Aborted."
    exit 2
fi

# If we're here, then everything went ok.

debug "Starting backup."

if [ ${gz} -eq "true" ]
    then
    dest="${dest}.gz"
fi

xterm -geometry 100x3+400+200 -T "PipeDroid Backup" -e ./pipedbackup_img "${part}" "${dest}" "${compression}"

debug "Backup back-end has died."

question "The backup has finished.\nDo you want to see the log to identify eventual issues?"
answer="${?}"
if [ ${answer} -eq 0 ]
    then
    cat $CFG/pipedroid.log | text
fi

exit 0